# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17R-JlkdbF9KFs_g61FNlB_csO1Tej8MH
"""

import pandas as pd
df = pd.read_csv('diabetes.csv')

print(df.head())

x = df.drop('Outcome',axis=1)
y = df['Outcome']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

y_predict = knn.predict(x_test)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

print("Accuracy: ",accuracy_score(y_test,y_predict)*100)
print("Precision: ",precision_score(y_test,y_predict))
print("Recall: ",recall_score(y_test,y_predict))
print("F1 Score: ",f1_score(y_test,y_predict))

import seaborn as sns
c = confusion_matrix(y_test,y_predict)
sns.heatmap(c,annot=True)