# -*- coding: utf-8 -*-
"""lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RyKX2iqIgW8Za7EOyuHbP5lP9mk83kpJ
"""

import pandas as pd
df = pd.read_csv('spamhamdata.csv',sep='\t',on_bad_lines='skip',names=['type','email'])

print(df.head())

df.info()

x=df['email']
y=df['type']

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True)
x_train_vec = vectorizer.fit_transform(x_train)
x_test_vec = vectorizer.transform(x_test)

from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(x_train_vec,y_train)

y_predict = model.predict(x_test_vec)

#Testing our model
sample_mail = pd.Series('XXX MobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. www.fraud.com?n=QJKGIGHJJGCBLMessage us to Bz-10567')
vec = vectorizer.transform(sample_mail)
model.predict(vec)[0]

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

print("Accuracy: ", accuracy_score(y_test, y_predict) * 100)
print("Precision: ", precision_score(y_test, y_predict, pos_label='spam'))
print("Recall: ", recall_score(y_test, y_predict, pos_label='spam'))
print("F1 Score: ", f1_score(y_test, y_predict, pos_label='spam'))