# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MKCuWyF5Fi3hXJxxys6XoFrWq6WbMSw-
"""

from sklearn.datasets import fetch_openml
mnist_data = fetch_openml('mnist_784',version=1)
print(mnist_data.keys())

x = mnist_data['data']
y = mnist_data['target']

x.shape, y.shape

sample = x.loc[[73]].to_numpy().reshape(28,28)

import matplotlib.pyplot as plt
plt.imshow(sample)

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.1)
x_train.shape

from sklearn.linear_model import SGDClassifier
model=SGDClassifier(random_state=42)
model.fit(x_train,y_train)

y_predict = model.predict(x_test)

from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

accuracy = accuracy_score(y_test, y_predict)
print(f"Accuracy: {accuracy*100}")

scores = cross_val_score(model, x, y, cv=5, scoring='accuracy')
print(f"Cross-validation scores: {scores}")
print(f"Mean cross-validation score: {scores.mean()}")

y_pred_cv = cross_val_predict(model, x, y, cv=5)
y_pred_cv

report = classification_report(y_test, y_predict)
print(report)

conf_matrix = confusion_matrix(y_test, y_predict)
print(conf_matrix)

import seaborn as sns
sns.heatmap(c, annot=True)