# -*- coding: utf-8 -*-
"""lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sra2GEcTbg9N2dyOm90akrBZW8bl-Fon
"""

import pandas as pd
data = pd.read_csv('salary.csv')
print(data.head())

x = data['exp(in months)'].values.reshape(-1,1)
y = data['salary(in thousands)'].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))
print("R-squared (R2) Score:", mean_squared_error(y_test, y_pred))

import matplotlib.pyplot as plt
plt.scatter(x_test, y_test, color='green')
plt.plot(x_test, y_pred, color='red', linewidth=3)
plt.xlabel('Experience')
plt.ylabel('Salary')
plt.title('Simple Linear Regression')
plt.show()