# -*- coding: utf-8 -*-
"""lab7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xiJ5FHND-vA3nUCPi6Ux38y2V2nFVRJC
"""

import pandas as pd
data = pd.read_csv('Housing.csv')
print(data.head())

from sklearn.preprocessing import OneHotEncoder
data_encoded = pd.get_dummies(data, drop_first=True)

x = data_encoded.drop('price', axis=1)  # Features
y = data_encoded['price']  # Target variable

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x = data.drop('price', axis=1)  # Features
y = data['price']  # Target variable

model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print("R-squared (R2) Score:", r2_score(y_test, y_pred))
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, y_pred))
print("Mean Squared Error (MSE):", mean_squared_error(y_test, y_pred))

import matplotlib.pyplot as plt
plt.scatter(y_test,y_pred,color="green")